### ISSUE TITLE
running the RSTP examples (redundant, triangle....)

### ISSUE THREAD

**Issue by qupfer** [aarizaq/inetmanet-3.x#3]
Hi, i'm new with omnet and inetmanet. 
I'm using omnet++ 4.2.2 on windows7 and also try ubuntu 12.04.

If i try the Spanning-Tree examples "out-of-the-box" i get errors like that directly after starting the simulation:
http://d.pr/i/F9B3

So i try to change the lines from something like "A.eth++ <---> B.eth++" to "A.eth++ <--> Eth100M <--> B.eth++" (i  have no idea if that makes sense) but yes it helps a bit. The error now is da differnt one and comes a few steps later
http://d.pr/i/xi1Q

Any ideas what i can do or how i get a working "STP-Switch" in omnet 4.2.2?

**Comment by aarizaq** [comment]
fixed
https://github.com/aarizaq/inetmanet-2.0/commit/f4392fe3947477a8577352e48f5b2aa4d022459c

Date: Sun, 21 Oct 2012 11:56:08 -0700

**Comment by qupfer** [comment]
wow thats fast, Thanks a lot
But the second "error" (http://d.pr/i/xi1Q) is still present

**Comment by mmasoumi** [comment]
I am new in Omnet++ and  I want to work on Rapid Spanning Tree , I have installed INETMANET on Ubunto 11.10
but I can not find RSPT examples or SPT .
Please help me
Sincerely
